version: '3'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "31337:31337"
    networks:
      - my-app-network


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge